### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by lxianl455** [LividWo/Revisit-MMT#1]
Hi, the resnet50-avgpool.npy link can not be accessed . Can you update a new one?

**Comment by LividWo** [comment]
Still work for me. Can you show a detailed error message?

**Comment by lxianl455** [comment]
![image](https://user-images.githubusercontent.com/63391363/221347482-f3e36f71-6c4e-4082-8873-6045ef813bc3.png)
I did use a VPN.
This is the first time I try to download an One-Drive file. I am not sure whether I miss the correct usage of the One-Drive .

**Comment by LividWo** [comment]
I tried on another machine, and it still works. So probably your local firewall prevent you from visiting onedrive.
